CREATE OR REPLACE CORTEX SEARCH SERVICE SOFTWARE_SALES_DEMO_DB.CUSTOMER_SERVICE.SERVICE_TICKET_SEARCH
  ON TICKET_DESCRIPTION
  ATTRIBUTES CUSTOMER_NAME, TICKET_DATE
  WAREHOUSE = SOFTWARE_SALES_DEMO_WH
  TARGET_LAG = '1 hour'
  EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
AS (
  SELECT
      CUSTOMER_NAME,
      TICKET_DATE,
      TICKET_DESCRIPTION
  FROM SOFTWARE_SALES_DEMO_DB.CUSTOMER_SERVICE.SERVICE_TICKETS
);

CREATE OR REPLACE CORTEX SEARCH SERVICE SOFTWARE_SALES_DEMO_DB.CUSTOMER_SERVICE.SERVICE_TICKET_SEARCH
  ON TICKET_DESCRIPTION
  ATTRIBUTES CUSTOMER_NAME, TICKET_DATE
  WAREHOUSE = SOFTWARE_SALES_DEMO_WH
  TARGET_LAG = '1 hour'
  EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
AS (
  SELECT
      CUSTOMER_NAME,
      TICKET_DATE,
      TICKET_DESCRIPTION
  FROM SOFTWARE_SALES_DEMO_DB.CUSTOMER_SERVICE.SERVICE_TICKETS
);